"""
Knowledge base fact write gate — state mutation policy for jingu-trust-gate.

Use case: a research agent proposes facts to write into a shared knowledge
base (wiki, structured DB, document store). Before any fact reaches storage,
the gate verifies that the fact is grounded in retrieved source material —
not generated by the LLM without evidence.

This is the "state" gating pattern applied to knowledge base writes:
controlling what enters the shared knowledge store is more important than
controlling what appears in a single response, because unverified facts
persist and accumulate.

Gate rules:
  R1  no retrieved source evidence at all           → UNSOURCED             → reject
  R2  claim is more specific than source supports   → OVER_SPECIFIC         → downgrade to "derived"
  R3  source is flagged as low-confidence           → LOW_CONFIDENCE_SOURCE → downgrade to "uncertain"
  R4  everything else                               → approve

Key idea:
  Unlike RAG responses (where a hallucinated fact affects one reply), a
  hallucinated KB write contaminates every future query that retrieves it.
  The gate enforces source grounding at the storage boundary.

Run:
  python examples/state/fact_write_policy.py
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Any, Optional

from jingu_trust_gate import (
    AdmittedUnit,
    AuditEntry,
    AuditWriter,
    ConflictAnnotation,
    GatePolicy,
    Proposal,
    RenderContext,
    RetryContext,
    RetryFeedback,
    SupportRef,
    StructureError,
    StructureValidationResult,
    UnitEvaluationResult,
    UnitWithSupport,
    VerifiedBlock,
    VerifiedContext,
    VerifiedContextSummary,
    create_trust_gate,
)
from jingu_trust_gate.helpers import (
    approve,
    reject,
    downgrade,
    first_failing,
    empty_proposal_errors,
    missing_id_errors,
    missing_text_field_errors,
)


# ── Domain types ───────────────────────────────────────────────────────────────

@dataclass
class FactWrite:
    id: str
    subject: str           # entity or topic the fact describes
    predicate: str         # relationship or property
    value: str             # the claim value
    grade: str             # "verified" | "derived" | "uncertain"
    evidence_refs: list[str]  # source_ids of retrieved sources that support this fact


# ── Policy ─────────────────────────────────────────────────────────────────────

class FactWritePolicy(GatePolicy[FactWrite]):

    def validate_structure(self, proposal: Proposal[FactWrite]) -> StructureValidationResult:
        errors: list[StructureError] = []
        errors.extend(empty_proposal_errors(proposal))
        if errors:
            return StructureValidationResult(valid=False, errors=errors)
        errors.extend(missing_id_errors(proposal.units))
        errors.extend(missing_text_field_errors(proposal.units, "subject", reason_code="MISSING_SUBJECT"))
        errors.extend(missing_text_field_errors(proposal.units, "predicate", reason_code="MISSING_PREDICATE"))
        return StructureValidationResult(valid=len(errors) == 0, errors=errors)

    def bind_support(self, unit: FactWrite, pool: list[SupportRef]) -> UnitWithSupport[FactWrite]:
        matched = [s for s in pool if s.source_id in unit.evidence_refs]
        return UnitWithSupport(unit=unit, support_ids=[s.id for s in matched], support_refs=matched)

    def evaluate_unit(self, uws: UnitWithSupport[FactWrite], ctx: dict) -> UnitEvaluationResult:
        return first_failing([
            self._check_source(uws),
            self._check_low_confidence(uws),
            self._check_over_specific(uws),
        ]) or approve(uws.unit.id)

    def _check_source(self, uws: UnitWithSupport[FactWrite]) -> Optional[UnitEvaluationResult]:
        """R1: at least one retrieved source must be bound."""
        if not uws.support_refs:
            return reject(
                uws.unit.id, "UNSOURCED",
                subject=uws.unit.subject,
                predicate=uws.unit.predicate,
                note=(
                    f'Fact "{uws.unit.subject} {uws.unit.predicate} {uws.unit.value}" '
                    "has no retrieved source. "
                    "Do not write unsourced facts into the knowledge base."
                ),
            )
        return None

    def _check_low_confidence(self, uws: UnitWithSupport[FactWrite]) -> Optional[UnitEvaluationResult]:
        """R3: low-confidence source → downgrade to uncertain."""
        low_conf = next(
            (s for s in uws.support_refs if s.attributes.get("confidence") == "low"),
            None,
        )
        if low_conf:
            return downgrade(
                uws.unit.id, "LOW_CONFIDENCE_SOURCE", "uncertain",
                source_title=low_conf.attributes.get("source_title", ""),
                note=(
                    f'Source "{low_conf.attributes.get("source_title")}" is marked low-confidence. '
                    'Downgraded to grade="uncertain" — KB should tag for re-verification.'
                ),
            )
        return None

    def _check_over_specific(self, uws: UnitWithSupport[FactWrite]) -> Optional[UnitEvaluationResult]:
        """R2: grade=verified but value not verbatim in any source excerpt → downgrade."""
        if uws.unit.grade == "verified":
            appears = any(
                uws.unit.value.lower() in s.attributes.get("excerpt", "").lower()
                for s in uws.support_refs
            )
            if not appears:
                return downgrade(
                    uws.unit.id, "OVER_SPECIFIC", "derived",
                    value=uws.unit.value,
                    note=(
                        f'Value "{uws.unit.value}" does not appear verbatim in any source excerpt. '
                        'Downgraded to grade="derived" — the fact was synthesized, not directly sourced.'
                    ),
                )
        return None

    def detect_conflicts(
        self, units: list[UnitWithSupport[FactWrite]], pool: list[SupportRef]
    ) -> list[ConflictAnnotation]:
        """Detect conflicting values for the same subject+predicate pair."""
        conflicts: list[ConflictAnnotation] = []
        seen: dict[str, UnitWithSupport[FactWrite]] = {}
        for uws in units:
            key = f"{uws.unit.subject}::{uws.unit.predicate}"
            prior = seen.get(key)
            if prior and prior.unit.value != uws.unit.value:
                conflicts.append(ConflictAnnotation(
                    unit_ids=[prior.unit.id, uws.unit.id],
                    conflict_code="CONFLICTING_VALUES",
                    sources=[*prior.support_ids, *uws.support_ids],
                    severity="informational",
                    description=(
                        f'Two facts assert different values for "{uws.unit.subject} {uws.unit.predicate}": '
                        f'"{prior.unit.value}" vs "{uws.unit.value}". '
                        "Both admitted with conflict note."
                    ),
                ))
            else:
                seen[key] = uws
        return conflicts

    def render(
        self, admitted_units: list[AdmittedUnit], pool: list[SupportRef], ctx: RenderContext
    ) -> VerifiedContext:
        blocks = []
        for u in admitted_units:
            fact = u.unit
            current_grade = u.applied_grades[-1] if u.applied_grades else fact.grade
            conflict = u.conflict_annotations[0] if u.conflict_annotations else None
            blocks.append(VerifiedBlock(
                source_id=u.unit_id,
                content=f"{fact.subject} | {fact.predicate} | {fact.value}",
                grade=current_grade,
                unsupported_attributes=(
                    [u.evaluation_results[0].reason_code]
                    if u.status == "downgraded" else []
                ),
                conflict_note=conflict.description if conflict else None,
            ))
        return VerifiedContext(
            admitted_blocks=blocks,
            summary=VerifiedContextSummary(
                admitted=len(admitted_units),
                rejected=0,
                conflicts=sum(1 for u in admitted_units if u.status == "approved_with_conflict"),
            ),
            instructions=(
                "Write only the verified facts below to the knowledge base. "
                'grade="derived" facts should be stored with a note that the value was synthesized. '
                'grade="uncertain" facts should be tagged for human re-verification. '
                "Facts with conflict notes should be reviewed before replacing existing KB entries."
            ),
        )

    def build_retry_feedback(
        self, unit_results: list[UnitEvaluationResult], ctx: RetryContext
    ) -> RetryFeedback:
        failed = [r for r in unit_results if r.decision == "reject"]
        return RetryFeedback(
            summary=(
                f"{len(failed)} fact write(s) rejected on attempt "
                f"{ctx.attempt}/{ctx.max_retries}. "
                "Every fact must be grounded in retrieved source material."
            ),
            errors=[
                {
                    "unitId": r.unit_id,
                    "reasonCode": r.reason_code,
                    "details": {
                        "hint": (
                            "Retrieve a source document and add its source_id to evidence_refs"
                            if r.reason_code == "UNSOURCED"
                            else "Review gate policy requirements"
                        ),
                    },
                }
                for r in failed
            ],
        )


# ── Noop audit writer ──────────────────────────────────────────────────────────

class NoopAuditWriter(AuditWriter):
    async def append(self, entry: AuditEntry) -> None:
        pass


# ── Helpers ────────────────────────────────────────────────────────────────────

def sep(title: str) -> None:
    print("\n" + "═" * 70)
    print(f"  {title}")
    print("═" * 70)


def subsep(title: str) -> None:
    print(f"\n  ── {title}")


def label(key: str, value: object) -> None:
    import json
    print(f"    {key:<34}: {json.dumps(value, ensure_ascii=False)}")


# ── Example run ────────────────────────────────────────────────────────────────

async def main() -> None:
    gate = create_trust_gate(policy=FactWritePolicy(), audit_writer=NoopAuditWriter())

    # ── Scenario A: Research agent proposes 4 KB facts ─────────────────────────
    #
    # Retrieved sources: two papers + one blog post.
    # fact-1: CO2 level (exact figure in source)          → APPROVE
    # fact-2: temperature rise (over-specific inference)  → DOWNGRADE (OVER_SPECIFIC)
    # fact-3: sea level rise (low-conf source)            → DOWNGRADE (LOW_CONFIDENCE_SOURCE)
    # fact-4: arctic ice melt year (no source at all)     → REJECT (UNSOURCED)

    sep("Scenario A — Research agent proposes 4 KB facts")

    pool_a = [
        SupportRef(
            id="ref-src-1", source_id="ipcc-ar6-ch2", source_type="observation",
            attributes={
                "source_title": "IPCC AR6 Chapter 2 — Changing State of the Climate System",
                "source_url": "https://example.com/ipcc-ar6-ch2",
                "excerpt": "Atmospheric CO2 concentration reached 410 ppm in 2019, the highest level in at least 2 million years.",
                "confidence": "high",
                "retrieved_at": "2024-01-15T10:00:00Z",
            },
        ),
        SupportRef(
            id="ref-src-2", source_id="nature-climate-proj", source_type="observation",
            attributes={
                "source_title": "Nature Climate Change — 2050 Temperature Projections",
                "source_url": "https://example.com/nature-climate-proj",
                "excerpt": "Under RCP 8.5, global mean surface temperature is projected to rise by 1.5–4.5°C by 2100 relative to 1850–1900.",
                "confidence": "medium",
                "retrieved_at": "2024-01-15T10:05:00Z",
            },
        ),
        SupportRef(
            id="ref-src-3", source_id="blog-climate-2023", source_type="observation",
            attributes={
                "source_title": "Climate Blog Post — 2023 Projections",
                "source_url": "https://example.com/blog-climate-2023",
                "excerpt": "Sea levels could rise between 0.3 and 1.0 meters by 2100 according to various models.",
                "confidence": "low",
                "retrieved_at": "2024-01-15T10:10:00Z",
            },
        ),
    ]

    print("\n  Retrieved sources:")
    for ref in pool_a:
        label(f"  {ref.source_id} [conf={ref.attributes['confidence']}]", ref.attributes["source_title"])

    proposal_a: Proposal[FactWrite] = Proposal(
        id="prop-kb-001", kind="response",
        units=[
            # fact-1: "410" appears verbatim in ipcc excerpt → APPROVE
            FactWrite(
                id="fact-1", subject="atmosphere",
                predicate="CO2_concentration_2019_ppm", value="410",
                grade="verified", evidence_refs=["ipcc-ar6-ch2"],
            ),
            # fact-2: "3.2" not in source (says 1.5–4.5) → DOWNGRADE (OVER_SPECIFIC)
            FactWrite(
                id="fact-2", subject="global_mean_surface_temperature",
                predicate="projected_rise_by_2100_celsius", value="3.2",
                grade="verified", evidence_refs=["nature-climate-proj"],
            ),
            # fact-3: low-confidence source → DOWNGRADE (LOW_CONFIDENCE_SOURCE)
            FactWrite(
                id="fact-3", subject="sea_level",
                predicate="projected_rise_by_2100_meters", value="0.3-1.0",
                grade="verified", evidence_refs=["blog-climate-2023"],
            ),
            # fact-4: no source in pool → REJECT (UNSOURCED)
            FactWrite(
                id="fact-4", subject="arctic_sea_ice",
                predicate="summer_free_year", value="2050",
                grade="verified", evidence_refs=[],
            ),
        ],
    )

    result_a = await gate.admit(proposal_a, pool_a)
    exp_a = gate.explain(result_a)

    subsep("OUTPUT: gate results")
    print("\n  Admitted facts:")
    for u in result_a.admitted_units:
        grade = u.applied_grades[-1] if u.applied_grades else u.unit.grade
        label(f"  {u.unit_id} [{u.status}, grade={grade}]",
              f"{u.unit.subject} {u.unit.predicate} = {u.unit.value}")
        if u.status == "downgraded":
            note = u.evaluation_results[0].annotations.get("note", "")
            if note:
                label("    note", note[:80])
    print("\n  Rejected facts:")
    for u in result_a.rejected_units:
        label(f"  {u.unit_id} [{u.evaluation_results[0].reason_code}]",
              f"{u.unit.subject} {u.unit.predicate} = {u.unit.value}")
        note = u.evaluation_results[0].annotations.get("note", "")
        if note:
            label("    note", note[:80])

    label("approved", exp_a.approved)
    label("downgraded", exp_a.downgraded)
    label("rejected", exp_a.rejected)

    assert exp_a.approved == 1, f"expected 1 approved, got {exp_a.approved}"
    assert exp_a.downgraded == 2, f"expected 2 downgraded, got {exp_a.downgraded}"
    assert exp_a.rejected == 1, f"expected 1 rejected, got {exp_a.rejected}"

    f2 = next(u for u in result_a.admitted_units if u.unit_id == "fact-2")
    assert f2.applied_grades[-1] == "derived"
    assert f2.evaluation_results[0].reason_code == "OVER_SPECIFIC"

    f3 = next(u for u in result_a.admitted_units if u.unit_id == "fact-3")
    assert f3.applied_grades[-1] == "uncertain"
    assert f3.evaluation_results[0].reason_code == "LOW_CONFIDENCE_SOURCE"

    f4 = next(u for u in result_a.rejected_units if u.unit_id == "fact-4")
    assert f4.evaluation_results[0].reason_code == "UNSOURCED"

    print("  [PASS] fact-1 (CO2=410ppm) approved — verbatim in IPCC excerpt")
    print("  [PASS] fact-2 (temp=3.2°C) downgraded to derived (OVER_SPECIFIC)")
    print("  [PASS] fact-3 (sea level) downgraded to uncertain (LOW_CONFIDENCE_SOURCE)")
    print("  [PASS] fact-4 (arctic ice) rejected (UNSOURCED)")

    # ── Scenario B: Conflicting facts for the same subject+predicate ─────────────
    #
    # Two sources give different values for the same fact.
    # Both admitted (informational conflict), both flagged with conflict note.

    sep("Scenario B — Conflicting facts for the same KB entry")

    pool_b = [
        SupportRef(
            id="ref-src-4", source_id="source-a", source_type="observation",
            attributes={
                "source_title": "Source A",
                "source_url": "https://example.com/a",
                "excerpt": "The global average temperature anomaly in 2023 was +1.45°C above pre-industrial levels.",
                "confidence": "high",
                "retrieved_at": "2024-01-15T11:00:00Z",
            },
        ),
        SupportRef(
            id="ref-src-5", source_id="source-b", source_type="observation",
            attributes={
                "source_title": "Source B",
                "source_url": "https://example.com/b",
                "excerpt": "2023 recorded a temperature anomaly of +1.48°C relative to the 1850–1900 baseline.",
                "confidence": "high",
                "retrieved_at": "2024-01-15T11:05:00Z",
            },
        ),
    ]

    proposal_b: Proposal[FactWrite] = Proposal(
        id="prop-kb-002", kind="response",
        units=[
            FactWrite(
                id="fact-5", subject="global_temperature_anomaly_2023",
                predicate="degrees_celsius_above_preindustrial", value="1.45",
                grade="verified", evidence_refs=["source-a"],
            ),
            FactWrite(
                id="fact-6", subject="global_temperature_anomaly_2023",
                predicate="degrees_celsius_above_preindustrial", value="1.48",
                grade="verified", evidence_refs=["source-b"],
            ),
        ],
    )

    result_b = await gate.admit(proposal_b, pool_b)
    exp_b = gate.explain(result_b)

    print("\n  Conflicting facts:")
    for u in result_b.admitted_units:
        label(f"  {u.unit_id} [{u.status}]", f"{u.unit.predicate} = {u.unit.value}")
        if u.conflict_annotations:
            label("    conflict", u.conflict_annotations[0].conflict_code)
    label("has_conflicts", result_b.has_conflicts)

    assert result_b.has_conflicts, "should have conflicts"
    assert len(result_b.admitted_units) == 2, "both facts should be admitted"
    print("  [PASS] fact-5 and fact-6 both admitted with CONFLICTING_VALUES note")
    print("  [PASS] informational conflict — KB writer should review before updating")

    print("\n  Done.\n")


if __name__ == "__main__":
    asyncio.run(main())
